export { Answer } from "./Answer";
export { Question } from "./Question";
export { HomeIcon } from "./HomeIcon";
export { Location } from "./Location";
export { Door } from "./Door";
export { People } from "./People";
export { Construction } from "./Construction";
export { Area } from "./Area";
export { Phone } from "./Phone";
export { Contact } from "./Contact";
export { Floor } from "./Floor";
export { Document } from "./Document";
export { Whatsapp } from "./Whatsapp";
export { Telegram } from "./Telegram";
// export {VectorArchLine} from './VectorArchLine';
export { ActiveDot } from "./ActiveDot";
export { ArrowLeft } from "./ArrowLeft";
export { ArrowRight } from "./ArrowRight";
export { DeactiveDot } from "./DeactiveDot";
// export {} from ".";
